apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-based-pv
  labels:
    PV: host-pv
spec:
  capacity:
    storage: 1Gi

  accessModes:
   - ReadWriteOnce

  hostPath:
   path: /home/devops/Day-14/PV
