apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-host-based

spec:
  resources:
    requests:
      storage: 500Mi

  selector:
    matchLabels:
      PV: host-pv

  accessModes:
   - ReadWriteOnce

