apiVersion: v1
kind: Pod
metadata:
  name: flask-pod
  labels:
     app: pod-flask

spec:
  containers:
    - name: flask-container
      image: flask-img:v1
      imagePullPolicy: Never
      ports:
         - containerPort: 5000
