apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment-loadbalacing

spec:
  replicas: 3

  selector:
    matchLabels:
        app: flask

  template:
    metadata:
      name: flask-pod
      labels:
        app: flask
    spec:
      containers:
          - name: flask-container
            image: aarun2786/flask-img:v2
            imagePullPolicy: Always
            ports:
             - containerPort: 5000
